'use strict';
const $=id=>document.getElementById(id),E=PanelEngine,A=CALC_DATA.entries,J=CALC_DATA.jades,KEY='naraka-panel-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n.toFixed(2)).toLocaleString('zh-CN',{maximumFractionDigits:2});
const fresh=()=>({version:1,slots:Array.from({length:7},()=>({jade:'',mode:'display',rows:Array.from({length:4},()=>({name:'',value:0}))})),base:{attack:'',atkBonus:0,hp:'',hpBonus:0,armor:'',crit:5,critDamage:150},active:{},manual:[],potentialPage:'current',critCap:true});
let config=fresh(),potential,readingError='';
try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.version===1&&Array.isArray(s.slots)&&s.slots.length===7&&s.slots.every(x=>['base','display'].includes(x.mode)&&Array.isArray(x.rows)&&x.rows.length===4&&x.rows.every(r=>typeof r.name==='string'&&Number.isFinite(Number(r.value))))&&s.base&&s.active&&Array.isArray(s.manual)&&s.manual.length<=50)config={...fresh(),...s};}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(config));$('saved').textContent='● 配装已自动保存'}catch{$('saved').textContent='自动保存不可用，请导出配装'}}
function read(){try{let s=JSON.parse(localStorage.getItem('naraka-potential-v3'));if(config.potentialPage==='none')s=null;else if(s&&config.potentialPage!=='current')s={...s,page:Number(config.potentialPage)};potential=E.readPotential(s,POTENTIAL_DATA);readingError='';}catch{potential=E.readPotential(null,POTENTIAL_DATA);readingError='潜能存档无法读取，未计入';}$('potential-state').textContent=readingError||potential.name+' · 已投入 '+potential.spent+'../48 点';}
const options=(selected,extra=false)=>'<option value="">选择属性</option>'+[...A.map(a=>a.name),...(extra?['元素暴击率','元素暴击伤害','元素伤害','招式伤害','伤害加成','受到的伤害减免','元素积累效率','灼烧伤害']:[])].map(n=>`<option ${n===selected?'selected':''}>${esc(n)}</option>`).join('');
const openSlots=new Set(config.slots.map((s,i)=>s.jade||i===0?String(i):null).filter(x=>x!==null));
window.addEventListener('foldchange',e=>{e.detail.open?openSlots.add(e.detail.key):openSlots.delete(e.detail.key)});
function renderSlots(){
 $('slots').innerHTML=config.slots.map((s,i)=>{const j=J.find(j=>j.id===s.jade);return `<article class="slot" data-slot="${i}"><div class="slot-head"><span class="slot-number">${String(i+1).padStart(2,'0')}</span><select data-jade="${i}" aria-label="魂玉栏位${i+1}"><option value="">${i===6?'选择招式专精魂玉':'选择魂玉'}</option>${J.map(j=>`<option value="${j.id}" ${s.jade===j.id?'selected':''} ${config.slots.some((other,k)=>k!==i&&other.jade===j.id)?'disabled':''}>${esc(j.name)}</option>`).join('')}</select></div><button class="fold-trigger" data-fold="${i}" aria-expanded="${openSlots.has(String(i))}" aria-controls="slot-content-${i}">词条配置 · ${s.rows.filter(r=>r.name).length}/4</button><div id="slot-content-${i}" class="fold-content ${openSlots.has(String(i))?'is-open':''}" ${openSlots.has(String(i))?'':'inert'}><div>${j?`<p class="slot-effect">${esc(j.effect)}</p>`:''}<div class="mode-line"><select data-mode="${i}" aria-label="第${i+1}栏数值口径"><option value="display" ${s.mode==='display'?'selected':''}>游戏显示值（已含合道）</option><option value="base" ${s.mode==='base'?'selected':''}>基础值（自动计算合道）</option></select><button data-full="${i}" ${!s.jade?'disabled':''}>已选词条填满</button></div>${s.rows.map((r,k)=>`<div class="affix-row"><select data-affix="${i},${k}" aria-label="第${i+1}栏词条${k+1}" ${!s.jade?'disabled':''}>${options(r.name)}</select><input type="number" min="0" step="any" data-value="${i},${k}" value="${esc(r.value)}" aria-label="第${i+1}栏词条${k+1}数值" ${!s.jade||!r.name?'disabled':''}><span class="unit">${A.find(a=>a.name===r.name)?.unit||''}</span><button data-max="${i},${k}" title="参考满值：显示模式包含本玉合道" aria-label="第${i+1}栏词条${k+1}填满" ${!s.jade||!r.name?'disabled':''}>满</button></div>`).join('')}<p class="hint">${s.mode==='display'?'按屏幕显示数值相加，不再重复应用合道。':'按本玉普通词条 ×（1 + 本玉合道之和）；重复合道规则待复核。'} 满值采用研究参考表。</p></div></div></article>`}).join('');
}
function renderBase(){const fields=[['attack','基础攻击（未加成）'],['atkBonus','永久攻击加成 %'],['hp','基础体力（未加成）'],['hpBonus','永久体力加成 %'],['armor','基础护甲'],['crit','基础暴击率 %'],['critDamage','基础暴伤总倍率 %']];$('base-fields').innerHTML=fields.map(([key,label])=>`<label class="base-field">${label}<input type="number" min="0" step="any" data-base="${key}" value="${esc(config.base[key])}" placeholder="未填写"></label>`).join('');$('crit-cap').checked=config.critCap;$('potential-page').value=config.potentialPage;}
function renderManual(){$('manual').innerHTML=config.manual.map((r,i)=>`<div class="manual-row"><select data-manual-name="${i}" aria-label="补充属性${i+1}">${options(r.name,true)}</select><input data-manual-value="${i}" type="number" step="any" value="${esc(r.value)}" aria-label="补充数值${i+1}"><span>${A.find(a=>a.name===r.name)?.unit||'%'}</span><button data-remove="${i}" aria-label="删除补充属性${i+1}">×</button></div>`).join('');}
function update(rebuildConditions=false){
 const result=E.calculate(config,potential,J,A);window.panelResult=result;
 for(const [id,value] of [['atk',`${result.atkBonus>=0?'+':''}${fmt(result.atkBonus)}<small>%</small>`],['crit',fmt(result.crit)+'<small>%</small>'],['crit-damage',fmt(result.critDamage)+'<small>%</small>'],['element',fmt(result.elementCrit)+'% / '+fmt(result.elementCritDamage)+'%']]){if($(id).innerHTML!==value){$(id).innerHTML=value;$(id).classList.remove('changed');requestAnimationFrame(()=>$(id).classList.add('changed'));}}
 $('attack-final').textContent=result.attack===null?'填写基础攻击可换算面板':'预估攻击 '+fmt(result.attack)+' · 永久加成 '+fmt(Number(config.base.atkBonus)||0)+'%';
 if(rebuildConditions)$('conditions').innerHTML=result.conditional.length?result.conditional.map(e=>`<label class="check"><input type="checkbox" data-active="${esc(e.id)}" ${config.active[e.id]?'checked':''}><span><strong>${esc(e.label)} · ${esc(e.stat)} ${e.value>=0?'+':''}${fmt(e.value)}%</strong>${esc(e.condition)}</span></label>`).join(''):'<p class="empty">配装或潜能中出现条件加成后，将在此列出。</p>';
 const keys=[...new Set([...Object.keys(result.totals),'攻击','暴击率','暴击伤害'])];$('count').textContent=keys.length+' 项属性';
 const unit=k=>A.find(a=>a.name===k)?.unit||'%';const cell=(n,k)=>n===undefined?'—':fmt(n)+unit(k);
 $('breakdown').innerHTML=keys.map(k=>`<tr><td>${esc(k)}</td><td>${cell(result.sub[k],k)}</td><td>${cell(result.main[k],k)}</td><td>${cell(result.pot[k],k)}</td><td>${cell(result.manual[k],k)}</td><td>${cell(result.totals[k]||0,k)}</td></tr>`).join('');
 const notes=[...result.notes];if(!potential.valid)notes.push(potential.name);if(result.hp!==null)notes.push('预估体力：'+fmt(result.hp));if(result.armor!==null)notes.push('预估护甲：'+fmt(result.armor));
 for(const s of config.slots){if(s.rows.filter(r=>r.name==='合道').length>1&&s.mode==='base')notes.push('存在重复合道：目前按相加估算，建议切换游戏显示值核对。');for(const r of s.rows){const a=A.find(a=>a.name===r.name);if(s.mode==='base'&&a&&Number(r.value)>a.max)notes.push(r.name+'超过参考基础满值，计算按'+a.max+a.unit+'计入。');}}
 $('notes').innerHTML=notes.map(n=>`<p class="warning">${esc(n)}</p>`).join('');
 const descriptions=[];for(const s of config.slots){const j=J.find(j=>j.id===s.jade);if(!j)continue;const modeled=E.MAIN[j.name]||j.name==='守缺化劲';descriptions.push(`<div class="unmodeled-item"><b>${esc(j.name)} · ${modeled?'面板部分已建模；其他机制看原效果':'主效果未自动折算，可补充已知数值'}</b><div>${esc(j.effect)}</div></div>`);}
 for(const p of potential.points.filter(p=>!p.data?.[2]&&!E.POT[p.code]))descriptions.push(`<div class="unmodeled-item"><b>${esc(p.data?.[0])} · ${p.code==='B6B'?'已处理体力转换':'特殊机制，未折算'}</b><div>${esc(p.data?.[1])}</div></div>`);
 $('unmodeled').innerHTML=descriptions.join('')||'<p class="empty">选择魂玉与潜能后查看。</p>';
 $('math').textContent='若枚卜两次判定独立，当前取优后的估算暴击率为 '+fmt(result.effectiveCrit)+'%，相对不暴击的期望倍率为 '+fmt(result.critExpected)+' 倍。该估算不包括元素专属暴击，且不代表实际总伤害提升。';
}
function maxRow(i,k){const s=config.slots[i],r=s.rows[k],a=A.find(a=>a.name===r.name);if(!a)return;r.value=a.max;if(s.mode==='display'&&a.kind==='普通副属性')r.value*=1+s.rows.filter(r=>r.name==='合道').reduce((v,r)=>v+Math.min(50,Math.max(0,Number(r.value)||0)),0)/100;}
document.addEventListener('change',e=>{const d=e.target.dataset;
 if(d.jade!==undefined){const i=Number(d.jade),next=J.find(j=>j.id===e.target.value);if(next){const conflict=config.slots.filter((_,k)=>k!==i).map(s=>J.find(j=>j.id===s.jade)).find(j=>j&&(next.effect.includes('无法同时装配')&&next.effect.slice(next.effect.indexOf('无法同时装配')).includes(j.name)||j.effect.includes('无法同时装配')&&j.effect.slice(j.effect.indexOf('无法同时装配')).includes(next.name)));if(conflict){alert('不能与已选择的「'+conflict.name+'」同时装配。');renderSlots();return;}}const expandOnSelect=!openSlots.has(String(i));config.slots[i].jade=e.target.value;Object.keys(config.active).filter(k=>k.startsWith('j:'+i+':')).forEach(k=>delete config.active[k]);renderSlots();if(expandOnSelect)requestAnimationFrame(()=>document.querySelector('[data-fold="'+i+'"]').click());}
 if(d.mode!==undefined){config.slots[Number(d.mode)].mode=e.target.value;renderSlots();}
 if(d.affix){const [i,k]=d.affix.split(',').map(Number);config.slots[i].rows[k]={name:e.target.value,value:0};renderSlots();}
 if(d.active)config.active[d.active]=e.target.checked;
 if(d.manualName!==undefined){config.manual[Number(d.manualName)].name=e.target.value;renderManual();}
 if(e.target.id==='potential-page'){config.potentialPage=e.target.value;read();}
 if(e.target.id==='crit-cap')config.critCap=e.target.checked;
 save();update(true);
});
document.addEventListener('input',e=>{const d=e.target.dataset;if(d.value){const [i,k]=d.value.split(',').map(Number);config.slots[i].rows[k].value=Math.max(0,Number(e.target.value)||0);}else if(d.base){config.base[d.base]=e.target.value===''?'':Math.max(0,Number(e.target.value)||0);}else if(d.manualValue!==undefined)config.manual[Number(d.manualValue)].value=Number(e.target.value)||0;else return;save();update();});
document.addEventListener('click',e=>{const d=e.target.dataset;if(d.max){maxRow(...d.max.split(',').map(Number));renderSlots();}else if(d.full!==undefined){const i=Number(d.full);config.slots[i].rows.filter(r=>r.name==='合道').forEach(r=>r.value=50);for(let k=0;k<4;k++)maxRow(i,k);renderSlots();}else if(d.remove!==undefined){config.manual.splice(Number(d.remove),1);renderManual();}else return;save();update(true);});
$('add-manual').onclick=()=>{if(config.manual.length>=50)return;config.manual.push({name:'攻击',value:0});renderManual();save();update();};
$('sync').onclick=()=>{read();update(true)};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({configuration:config,potentialSnapshot:potential,summary:window.panelResult},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='征神配装面板.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
window.addEventListener('storage',e=>{if(e.key==='naraka-potential-v3'){read();update(true)}});window.addEventListener('focus',()=>{read();update(true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden){read();update(true)}});
read();renderSlots();renderBase();renderManual();update(true);
