'use client';
import { useState, useEffect } from 'react';
import { Search, ArrowUpRight, SlidersHorizontal, Gem, BookOpen, RotateCcw, ChevronRight } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Pagination, PaginationContent, PaginationItem, PaginationLink } from '@/components/ui/pagination';
import jades from '@/data/jades.json';
import affixes from '@/data/affixes.json';
import { filterEntries, categoryOptions, subcategoryOptions } from '@/lib/atlas';
const source = 'https://www.yjwujian.cn/news/update/20260817/33456_1311350.html';
const attributes = affixes.map((a, i) => ({ id: 'affix-' + i, name: a.name, kind: '词条', effect: a.name === '枚卜' ? '双次暴击取优判定概率：单条满值参考20%，总生效上限100%。该概率不等于暴击率。' : a.name === '合道' ? '单条满值参考50%。提升本魂玉普通副属性，游戏显示值模式下不要重复应用。' : a.name === '化气' ? '单条满值参考25%。触发对应元素效果时减少技能剩余冷却；与技能冷却速度分开。' : a.name === '火正' ? '单条满值参考3级。振刀后的攻击附带灼烧，条件效果不计入常驻攻击。' : a.name + '：单条基础满值参考 ' + a.max + a.unit + '，不含合道。', icon: '', element: '通用', classifications: [{ category: '词条', subcategory: a.kind }], sources: [] as typeof jades[number]['sources'], incomplete: false, note: a.status }));
const records = [...jades, ...attributes];
type Entry = typeof records[number];
export default function Home() {
    const [pageSize, setPageSize] = useState(() => window.matchMedia('(max-width:760px)').matches ? 12 : 24);
    useEffect(() => {
        const media = window.matchMedia('(max-width:760px)');
        const resize = () => { setPageSize(media.matches ? 12 : 24); setPage(1); };
        media.addEventListener('change', resize);
        return () => media.removeEventListener('change', resize);
    }, []);
    const [tab, setTab] = useState('魂玉'), [query, setQuery] = useState(''), [category, setCategory] = useState('全部'), [subcategory, setSubcategory] = useState('全部'), [element, setElement] = useState('全部'), [page, setPage] = useState(1), [selected, setSelected] = useState<Entry | null>(null);
    useEffect(() => { if (new URLSearchParams(window.location.search).get('tab') === 'attributes')
        setTab('词条'); }, []);
    const [detailOpen, setDetailOpen] = useState(false);
    const reset = () => { setQuery(''); setCategory('全部'); setSubcategory('全部'); setElement('全部'); setPage(1); };
    const results = filterEntries(records, { tab, query, category, subcategory, element });
    const pages = Math.max(1, Math.ceil(results.length / pageSize));
    const current = Math.min(page, pages);
    const pageNumbers = Array.from({length: pages}, (_, i) => i + 1).filter(n => pages <= 7 || n === 1 || n === pages || Math.abs(n - current) <= 1);
    const visible = results.slice((current - 1) * pageSize, current * pageSize);
    const changePage = (n: number) => { setPage(n); document.getElementById('results-heading')?.scrollIntoView({ behavior: 'instant', block: 'start' }); };
    return <div className="site-shell"><header className="topbar"><a href="./" className="brand" aria-label="征神图鉴首页"><img src="./logo.png" alt="永劫无间"/><span className="brand-divider"/><span>征神图鉴<small>SOULJADE ARCHIVE</small></span></a><a className="blog-return" href="../works.html">返回作品</a><a className="official" href={source} target="_blank" rel="noreferrer">官方更新公告 <ArrowUpRight size={16}/></a></header>
 <main><section className="hero"><div className="hero-content"><p className="eyebrow"><span /> 万象藏于玉 · 征途自此明</p><h1>征神图鉴</h1><span className="archive-seal" aria-hidden="true">秘卷</span><p className="hero-copy">阅魂玉百相，循潜能经脉。</p></div><div className="season"><span>游戏截图资料</span><strong>S6 <i>红砂</i></strong><small>收集日期 2026.09.07 — 09.10</small></div></section>
 <div className="notice"><span className="notice-label">魂玉图鉴</span><p>已收录 {jades.length} 枚魂玉，含外观与效果。暂不含赛季纪念魂玉；「四灵归极」下半段效果待补图。</p></div>
 <Tabs value={tab} onValueChange={v => { setTab(String(v)); reset(); }} className="archive"><div className="archive-heading"><TabsList className="archive-tabs" variant="line">{['魂玉', '天赋', '词条'].map((t, i) => t === '天赋' ? <a key={t} className="potential-tab" href="./potential/index.html"><BookOpen />潜能推演<small>48点</small></a> : <TabsTrigger key={t} value={t}>{i === 0 ? <Gem /> : i === 1 ? <BookOpen /> : <SlidersHorizontal />}{t}{t !== '天赋' && <small>{t === '魂玉' ? jades.length : affixes.length}</small>}</TabsTrigger>)}</TabsList><a className="edition atlas-potential-link" href="./calculator/index.html">配装面板 <ChevronRight size={14}/></a></div>
 {['魂玉', '词条'].filter(t => t === tab).map(t => <TabsContent key={t} value={t}><div className="workspace"><aside className="filters"><div className="filter-title"><span><SlidersHorizontal size={16}/>分门查阅</span><button onClick={reset} title="重置筛选" aria-label="重置筛选"><RotateCcw size={15}/></button></div>
 <div className="filter-fields"><label className="filter-field">魂玉分类<NativeSelect value={category} onChange={e => { setCategory(e.target.value); setSubcategory('全部'); setPage(1); }} disabled={t !== '魂玉'}>{['全部', ...categoryOptions].map(c => <NativeSelectOption key={c} value={c}>{c === '全部' ? '全部分类' : c}{c !== '全部' ? ` · ${jades.filter(r => r.classifications.some(x => x.category === c)).length}` : ''}</NativeSelectOption>)}</NativeSelect></label>
 <label className="filter-field">细分类型<NativeSelect value={subcategory} onChange={e => { setSubcategory(e.target.value); setPage(1); }} disabled={t !== '魂玉'}>{['全部', ...subcategoryOptions(jades, category)].map(c => <NativeSelectOption key={c} value={c}>{c === '全部' ? '全部类型' : c}</NativeSelectOption>)}</NativeSelect></label>
 <label className="filter-field">元素关联<NativeSelect value={element} onChange={e => { setElement(e.target.value); setPage(1); }} disabled={t !== '魂玉'}>{['全部', '通用', '冰', '电', '毒', '随词条变化'].map(c => <NativeSelectOption key={c} value={c}>{c === '全部' ? '全部元素' : c}</NativeSelectOption>)}</NativeSelect></label></div>
 <div className="filter-note"><BookOpen size={20}/><strong>知玉，方能破境。</strong><p>按收集目录分类。跨分类魂玉合并为一个条目，在各所属分类均可找到。</p><p>效果按截图记录，详情可查看原图。</p></div></aside>
 <section className="results"><label className="search"><Search size={21}/><input value={query} onChange={e => { setQuery(e.target.value); setPage(1); }} placeholder={`查阅${t} · 名称或效果…`} aria-label={`搜索${t}`}/>{query && <button onClick={() => { setQuery(''); setPage(1); }} aria-label="清空搜索">清空</button>}<span className="search-hint">查阅秘卷</span></label>
 <div className="result-heading" id="results-heading"><h2>{t}图鉴 <span>/ {t === '魂玉' ? 'SOULJADES' : t === '天赋' ? 'TALENTS' : 'ATTRIBUTES'}</span></h2><span aria-live="polite">共 <b>{results.length}</b> 项{results.length > pageSize ? ` · 第 ${current}/${pages} 页` : ''}</span></div>
 {visible.length ? <div className="card-grid">{visible.map((r) => <button key={r.id} data-category={r.classifications[0].category} className={'jade-card element-' + r.element} onClick={() => { setSelected(r); setDetailOpen(true); }} aria-label={`查看${r.name}效果`}><div className="card-top"><span className="card-number">卷录 · {String(records.findIndex(entry => entry.id === r.id) + 1).padStart(3, '0')}</span><span className={'new-tag ' + (r.incomplete ? 'pending-tag' : '')}>{r.incomplete ? '效果待补全' : r.classifications[0].category}</span></div><div className="jade-art">{r.icon ? <img src={r.icon} alt={`${r.name}魂玉外观`} width={90} height={90} loading="lazy"/> : <Gem size={42} strokeWidth={1}/>}</div><div className="card-body"><div className="card-category">{r.classifications.map(c => c.subcategory).join(' / ')}</div><h3>{r.name}</h3><p className="effect-preview">{r.effect}</p><div className="card-bottom"><span>{r.element}</span><span className="view-detail">查看效果 <ArrowUpRight size={16}/></span></div></div></button>)}</div> : <div className="empty"><BookOpen size={38}/><h3>{t === '天赋' ? '天赋图鉴，静候开卷' : '此卷未录'}</h3><p>{t === '天赋' ? '天赋检索入口已就绪，完整名称、效果与解锁条件待资料补充。' : '试试其他名称、效果关键词，或重置筛选条件。'}</p>{t !== '天赋' && <button onClick={reset}>重置筛选</button>}</div>}
 {pages > 1 && <Pagination className="atlas-pagination" aria-label="魂玉图鉴分页"><PaginationContent><PaginationItem><button disabled={current === 1} onClick={() => changePage(current - 1)} aria-label="上一页">← 上一卷</button></PaginationItem>{pageNumbers.map((n, i) => <PaginationItem key={n}>{i > 0 && n - pageNumbers[i - 1] > 1 && <span className="page-gap" aria-hidden="true">…</span>}<PaginationLink href="#results-heading" isActive={current === n} onClick={e => { e.preventDefault(); changePage(n); }} aria-label={`第 ${n} 页`}>{n}</PaginationLink></PaginationItem>)}<PaginationItem><button disabled={current === pages} onClick={() => changePage(current + 1)} aria-label="下一页">下一卷 →</button></PaginationItem></PaginationContent></Pagination>}
 <div className="end-note"><span />{results.length ? `展示 ${(current - 1) * pageSize + 1}–${Math.min(current * pageSize, results.length)} / ${results.length} 项` : '资料持续整理中'}<span /></div></section></div></TabsContent>)}
 </Tabs></main><footer><span>征神图鉴 <i> / </i> 玩家资料站 · 非官方网站</span><span>游戏名称、Logo 与素材归原权利人所有</span></footer>
 <Sheet open={detailOpen} onOpenChange={setDetailOpen}><SheetContent className="detail-sheet"><SheetHeader><p className="eyebrow">征神之路 / {selected?.kind}</p><div className="detail-identity">{selected?.icon && <img src={selected.icon} alt={`${selected.name}魂玉外观`} width={90} height={90}/>}<SheetTitle className="detail-title">{selected?.name}</SheetTitle></div><SheetDescription>{selected?.classifications.map(c => `${c.category} / ${c.subcategory}`).join(' · ')}</SheetDescription></SheetHeader><div className="detail-body"><span className="detail-label">魂玉效果</span><p className="full-effect">{selected?.effect}</p>{selected?.incomplete && <div className="incomplete-note">{selected.note}</div>}
 {selected?.sources.length ? <div className="detail-source"><h3>游戏内原始截图</h3><p>文字按收集截图整理；点击图片可查看大图。</p>{selected.sources.map(s => <figure key={s.image}><a href={s.image} target="_blank" rel="noreferrer"><img src={s.image} alt={`${selected.name}原始效果截图，${s.category}/${s.subcategory}`} loading="lazy"/></a><figcaption>{s.category} / {s.subcategory} · {s.date}</figcaption></figure>)}</div> : <div className="detail-source"><h3>资料依据</h3><p>{selected?.note}。普通满值来自社区参考表，尚未全部通过当前游戏版本复核。</p><a href="https://yongjiewujian.net/" target="_blank" rel="noreferrer">查看满值参考表 <ArrowUpRight size={16}/></a><p><a href="./calculator/index.html">进入实时配装面板 →</a></p>{selected?.name === '枚卜' && <a href="https://news.17173.com/content/08312026/185028474.shtml" target="_blank" rel="noreferrer">枚卜数值与机制来源</a>}</div>}
 </div></SheetContent></Sheet></div>;
}
