const {chromium}=require('C:/Users/emmmm/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1440,height:900},serviceWorkers:'block'});await context.route('**/*',r=>['GET','HEAD','OPTIONS'].includes(r.request().method())?r.continue():r.abort());const out=path.resolve('screenshots/live-service');fs.mkdirSync(out,{recursive:true});const results=[];
for(const file of ['articles.html','videos.html']){const page=await context.newPage(),failures=[];page.on('requestfailed',r=>{if(r.method()==='GET')failures.push({url:r.url(),error:r.failure()?.errorText})});await page.goto('http://localhost:8000/'+file);await page.waitForTimeout(11500);await page.screenshot({path:path.join(out,file+'.png'),fullPage:true});results.push({file,text:await page.locator('main').innerText(),failures});
const card=page.locator(file==='articles.html'?'.article-list-card':'.video-card').first();
if(await card.count()){const href=await card.getAttribute('href');await page.goto(new URL(href,page.url()).href);await page.locator('.article-body').waitFor({timeout:20000});await page.waitForTimeout(1500);const detail={file:page.url(),text:(await page.locator('main').innerText()).slice(0,1000)};
if(file==='videos.html'){try{await page.locator('video').evaluate(async video=>{video.muted=true;await video.play()},{timeout:15000});await page.waitForTimeout(1800);detail.playback=await page.locator('video').evaluate(v=>({time:v.currentTime,duration:v.duration,error:v.error?.message}));await page.locator('video').evaluate(v=>v.pause())}catch(e){detail.playbackError=e.message}}
await page.screenshot({path:path.join(out,file+'-detail.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,file+'-detail-mobile.png'),fullPage:true});detail.mobileWidth=await page.evaluate(()=>document.documentElement.scrollWidth);results.push(detail)}
await page.close()}
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
