const {chromium}=require('C:/Users/emmmm/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {installFixtures}=require('./review-fixtures.cjs');const fs=require('fs'),assert=require('assert');
const out='screenshots/issue-2/room';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const report=[];
for(const [width,height] of [[1920,1200],[390,844],[768,1024]]){
 const c=await b.newContext({viewport:{width,height},serviceWorkers:'block',reducedMotion:'reduce'});await c.route('**/*',r=>['GET','HEAD','OPTIONS'].includes(r.request().method())?r.continue():r.abort());await installFixtures(c,{origin:'http://127.0.0.1:8123'});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8123/articles.html',{waitUntil:'domcontentloaded'});await p.waitForTimeout(1800);await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:`${out}/articles-${width}.png`,fullPage:true});
 const article=await p.locator('.article-list-card').first().evaluate(e=>{const v=e.querySelector('.article-list-cover').getBoundingClientRect(),t=e.querySelector('.article-list-copy').getBoundingClientRect();return {coverLeft:v.left,textLeft:t.left,coverTop:v.top,textTop:t.top}});assert(width<=560?article.coverTop<article.textTop:article.coverLeft<article.textLeft);
 await p.goto('http://127.0.0.1:8123/pet.html',{waitUntil:'domcontentloaded'});await p.waitForTimeout(6500);if(await p.locator('#petEntrySkip').isVisible())await p.locator('#petEntrySkip').click();await p.evaluate(()=>document.fonts.ready);assert(await p.locator('.live2d-canvas').count()>0);
 const getScene=()=>p.locator('#petRoom').getAttribute('data-time-scene');
 for(const scene of ['day','night']){for(let i=0;await getScene()!==scene&&i<4;i++)await p.locator('#sceneToggle').click();assert.equal(await getScene(),scene);await p.waitForTimeout(1500);await p.evaluate(t=>{document.documentElement.dataset.theme=t;scrollTo(0,0)},scene==='night'?'dark':'light');await p.waitForTimeout(250);await p.screenshot({path:`${out}/pet-${width}-${scene}.png`,fullPage:true});const bg=await p.locator('.room-scenery').evaluate(e=>getComputedStyle(e).backgroundImage);assert(bg.includes(scene==='night'?'pet-room-night':width<=620?'pet-room-mobile':'pet-room-day'));}
 await p.locator('.status-card summary').click();await p.locator('#petRoom').screenshot({path:`${out}/status-${width}.png`});assert(await p.locator('#petXpText').isVisible());await p.locator('.status-card summary').click();
 await p.locator('[data-action="pet"]').click();await p.waitForFunction(()=>!document.querySelector('[data-action="pet"]').disabled);await p.locator('#resetPosition').click();await p.locator('#motionToggle').click();assert.equal(await p.locator('#motionToggle').getAttribute('aria-pressed'),'false');await p.locator('#motionToggle').click();await p.locator('#soundToggle').click();await p.locator('#visitToggle').click();await p.waitForFunction(()=>document.querySelector('#profileName').textContent!=='小桃');
 const checks=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,smallButtons:[...document.querySelectorAll('.control-card button, .status-card summary')].filter(e=>{const r=e.getBoundingClientRect();return r.width<44||r.height<44}).map(e=>e.id||e.textContent),broken:[...document.images].filter(i=>i.getAttribute('src')&&i.complete&&!i.naturalWidth).map(i=>i.src)}));report.push({width,height,article,errors,...checks});console.log(report.at(-1));fs.writeFileSync(out+'/results.json',JSON.stringify(report,null,2));await c.close();
}await b.close();assert(report.every(r=>!r.overflow&&!r.errors.length&&!r.smallButtons.length&&!r.broken.length));})().catch(e=>{console.error(e);process.exit(1)});
